#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

function clone_repo {
	owner=$1
	name=$2
	sha=$3

	path=examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone --depth 1 "https://github.com/$owner/$name" "$path"
	fi

	pushd "$path" >/dev/null
	actual_sha=$(git rev-parse HEAD)
	if [ "$actual_sha" != "$sha" ]; then
		echo "Updating $owner/$name to $sha"
		git fetch --depth 1 origin "$sha"
		git reset --hard "$sha"
	fi
	popd >/dev/null
}

clone_repo laravel laravel 9d0862b3340c8243ee072afc181e315ffa35e110
clone_repo laravel framework 45d439e98a6b14afde8911f7d22a265948adbf72
clone_repo phacility phabricator d0b01a41f2498fb2a6487c2d6704dc7acfd4675f
clone_repo sebastianbergmann phpunit 5e523bdc7dd4d90fed9fb29d1df05347b3e7eaba
clone_repo WordPress WordPress 45286c5bb3f6fe5005567903ec858d87077eae2c
clone_repo wikimedia mediawiki b6b88cbf98fb0c7891324709a85eabc290ed28b4

known_failures=$(cat script/known-failures.txt)

# shellcheck disable=2046
tree-sitter parse -q \
	examples/**/*.php \
	$(for file in $known_failures; do echo "!${file}"; done)

example_count=$(find examples -name '*.php' | wc -l)
failure_count=$(wc -w <<<"$known_failures")
success_count=$((example_count - failure_count))
success_percent=$(bc -l <<<"100*${success_count}/${example_count}")

printf \
	"Successfully parsed %d of %d example files (%.1f%%)\n" \
	$success_count $example_count $success_percent
