[package]
name = "tree-sitter-typescript"
description = "Typescript grammar for tree-sitter"
version = "0.20.5"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
license = "MIT"
readme = "bindings/rust/README.md"
keywords = ["incremental", "parsing", "typescript", "tsx"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-typescript"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
	"common",
	"bindings/rust",
	"typescript/grammar.js",
	"typescript/src",
	"tsx/grammar.js",
	"tsx/src",
	"queries",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20"

[build-dependencies]
cc = "~1.0.83"
