[package]
name = "marzano-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = { path = "../../vendor/tree-sitter-facade", package = "tree-sitter-facade-sg" }
serde = { version = "1.0.164", features = ["derive"] }
base64 = "0.21.2"
anyhow = "1.0.70"
log = { version = "0.4.20", optional = true }
ignore = { version = "0.4.21", optional = true }
sha2 = { version = "0.10.8" }
derive_builder = "0.13.1"
tree-sitter-traversal = { version = "0.1.2", default-features = false }
reqwest = { version = "0.11.22", features = [
  "blocking",
  "json",
], optional = true }
tokio = { version = "1.35.1", optional = true }
serde_json = "1.0.114"
futures = "0.3.29"
http = "0.2.11"

[features]
finder = ["log", "ignore"]

network_requests_common = []
network_requests = ["reqwest", "tokio", "tokio/rt", "network_requests_common"]
network_requests_external = ["network_requests_common"]
