[package]
name = "tree-sitter-ruby"
description = "Ruby grammar for tree-sitter"
version = "0.20.1"
authors = [
	"Douglas Creager <dcreager@dcreager.net>",
	"Max Brunsfeld <maxbrunsfeld@gmail.com>",
]
license = "MIT"
readme = "bindings/rust/README.md"
keywords = ["incremental", "parsing", "ruby"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-ruby"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20"

[build-dependencies]
cc = "1.0.83"
