[package]
name = "tree-sitter-javascript"
description = "JavaScript grammar for tree-sitter"
version = "0.20.3"
authors = [
	"Max Brunsfeld <maxbrunsfeld@gmail.com>",
	"Douglas Creager <dcreager@dcreager.net>",
	"Amaan Qureshi <amaanq12@gmail.com>",
]
license = "MIT"
readme = "bindings/rust/README.md"
keywords = ["incremental", "parsing", "javascript"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-javascript"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20"
[build-dependencies]
cc = "~1.0.83"
