name: JavaScript SDK

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: namespace-profile-standard-ubuntu22-amd64
    steps:
      - name: clone code
        uses: namespacelabs/nscloud-checkout-action@v4
        with:
          submodules: recursive
      - name: install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-11-16
          override: true
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: build Node API
        working-directory: ./js/node-api
        run: bun run build
      - name: test Node API
        working-directory: ./js/node-api
        run: bun test
